# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TransparencySetter
                                 A QGIS plugin
 Apply the specified transparency value to both vector and raster layers, as well as layers within the selected groups in the Layer Panel
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-05-10
        copyright            : (C) 2023 by Idrostudi Srl
        email                : martinis@idrostudi.it
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TransparencySetter class from file TransparencySetter.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .transparency_setter import TransparencySetter
    return TransparencySetter(iface)
